apiVersion: "v1"
kind: Namespace
metadata:
  name: httpbin
---
kind: "Pod"
apiVersion: "v1"
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  containers:
  - name: httpbin
    image: kennethreitz/httpbin
    ports:
    - name: http
      containerPort: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: httpbin
  namespace: httpbin
spec:
  selector:
    app: httpbin
  type: "LoadBalancer"
  ports:
  - port: 80
    targetPort: 80
